#[cfg(feature = "OVR+OpenVR+InputOriginInfo_t")]
#[repr(C)]
#[derive(Debug, Clone, Default, PartialEq)]
pub struct InputOriginInfo_t {
    pub devicePath: u64,
    pub trackedDeviceIndex: u32,
    pub rchRenderModelComponentName0: u8,
    pub rchRenderModelComponentName1: u8,
    pub rchRenderModelComponentName2: u8,
    pub rchRenderModelComponentName3: u8,
    pub rchRenderModelComponentName4: u8,
    pub rchRenderModelComponentName5: u8,
    pub rchRenderModelComponentName6: u8,
    pub rchRenderModelComponentName7: u8,
    pub rchRenderModelComponentName8: u8,
    pub rchRenderModelComponentName9: u8,
    pub rchRenderModelComponentName10: u8,
    pub rchRenderModelComponentName11: u8,
    pub rchRenderModelComponentName12: u8,
    pub rchRenderModelComponentName13: u8,
    pub rchRenderModelComponentName14: u8,
    pub rchRenderModelComponentName15: u8,
    pub rchRenderModelComponentName16: u8,
    pub rchRenderModelComponentName17: u8,
    pub rchRenderModelComponentName18: u8,
    pub rchRenderModelComponentName19: u8,
    pub rchRenderModelComponentName20: u8,
    pub rchRenderModelComponentName21: u8,
    pub rchRenderModelComponentName22: u8,
    pub rchRenderModelComponentName23: u8,
    pub rchRenderModelComponentName24: u8,
    pub rchRenderModelComponentName25: u8,
    pub rchRenderModelComponentName26: u8,
    pub rchRenderModelComponentName27: u8,
    pub rchRenderModelComponentName28: u8,
    pub rchRenderModelComponentName29: u8,
    pub rchRenderModelComponentName30: u8,
    pub rchRenderModelComponentName31: u8,
    pub rchRenderModelComponentName32: u8,
    pub rchRenderModelComponentName33: u8,
    pub rchRenderModelComponentName34: u8,
    pub rchRenderModelComponentName35: u8,
    pub rchRenderModelComponentName36: u8,
    pub rchRenderModelComponentName37: u8,
    pub rchRenderModelComponentName38: u8,
    pub rchRenderModelComponentName39: u8,
    pub rchRenderModelComponentName40: u8,
    pub rchRenderModelComponentName41: u8,
    pub rchRenderModelComponentName42: u8,
    pub rchRenderModelComponentName43: u8,
    pub rchRenderModelComponentName44: u8,
    pub rchRenderModelComponentName45: u8,
    pub rchRenderModelComponentName46: u8,
    pub rchRenderModelComponentName47: u8,
    pub rchRenderModelComponentName48: u8,
    pub rchRenderModelComponentName49: u8,
    pub rchRenderModelComponentName50: u8,
    pub rchRenderModelComponentName51: u8,
    pub rchRenderModelComponentName52: u8,
    pub rchRenderModelComponentName53: u8,
    pub rchRenderModelComponentName54: u8,
    pub rchRenderModelComponentName55: u8,
    pub rchRenderModelComponentName56: u8,
    pub rchRenderModelComponentName57: u8,
    pub rchRenderModelComponentName58: u8,
    pub rchRenderModelComponentName59: u8,
    pub rchRenderModelComponentName60: u8,
    pub rchRenderModelComponentName61: u8,
    pub rchRenderModelComponentName62: u8,
    pub rchRenderModelComponentName63: u8,
    pub rchRenderModelComponentName64: u8,
    pub rchRenderModelComponentName65: u8,
    pub rchRenderModelComponentName66: u8,
    pub rchRenderModelComponentName67: u8,
    pub rchRenderModelComponentName68: u8,
    pub rchRenderModelComponentName69: u8,
    pub rchRenderModelComponentName70: u8,
    pub rchRenderModelComponentName71: u8,
    pub rchRenderModelComponentName72: u8,
    pub rchRenderModelComponentName73: u8,
    pub rchRenderModelComponentName74: u8,
    pub rchRenderModelComponentName75: u8,
    pub rchRenderModelComponentName76: u8,
    pub rchRenderModelComponentName77: u8,
    pub rchRenderModelComponentName78: u8,
    pub rchRenderModelComponentName79: u8,
    pub rchRenderModelComponentName80: u8,
    pub rchRenderModelComponentName81: u8,
    pub rchRenderModelComponentName82: u8,
    pub rchRenderModelComponentName83: u8,
    pub rchRenderModelComponentName84: u8,
    pub rchRenderModelComponentName85: u8,
    pub rchRenderModelComponentName86: u8,
    pub rchRenderModelComponentName87: u8,
    pub rchRenderModelComponentName88: u8,
    pub rchRenderModelComponentName89: u8,
    pub rchRenderModelComponentName90: u8,
    pub rchRenderModelComponentName91: u8,
    pub rchRenderModelComponentName92: u8,
    pub rchRenderModelComponentName93: u8,
    pub rchRenderModelComponentName94: u8,
    pub rchRenderModelComponentName95: u8,
    pub rchRenderModelComponentName96: u8,
    pub rchRenderModelComponentName97: u8,
    pub rchRenderModelComponentName98: u8,
    pub rchRenderModelComponentName99: u8,
    pub rchRenderModelComponentName100: u8,
    pub rchRenderModelComponentName101: u8,
    pub rchRenderModelComponentName102: u8,
    pub rchRenderModelComponentName103: u8,
    pub rchRenderModelComponentName104: u8,
    pub rchRenderModelComponentName105: u8,
    pub rchRenderModelComponentName106: u8,
    pub rchRenderModelComponentName107: u8,
    pub rchRenderModelComponentName108: u8,
    pub rchRenderModelComponentName109: u8,
    pub rchRenderModelComponentName110: u8,
    pub rchRenderModelComponentName111: u8,
    pub rchRenderModelComponentName112: u8,
    pub rchRenderModelComponentName113: u8,
    pub rchRenderModelComponentName114: u8,
    pub rchRenderModelComponentName115: u8,
    pub rchRenderModelComponentName116: u8,
    pub rchRenderModelComponentName117: u8,
    pub rchRenderModelComponentName118: u8,
    pub rchRenderModelComponentName119: u8,
    pub rchRenderModelComponentName120: u8,
    pub rchRenderModelComponentName121: u8,
    pub rchRenderModelComponentName122: u8,
    pub rchRenderModelComponentName123: u8,
    pub rchRenderModelComponentName124: u8,
    pub rchRenderModelComponentName125: u8,
    pub rchRenderModelComponentName126: u8,
    pub rchRenderModelComponentName127: u8,
}
#[cfg(feature = "OVR+OpenVR+InputOriginInfo_t")]
quest_hook::libil2cpp::unsafe_impl_value_type!(
    in quest_hook::libil2cpp for crate ::OVR::OpenVR::InputOriginInfo_t => "OVR.OpenVR"
    ."InputOriginInfo_t"
);
#[cfg(feature = "OVR+OpenVR+InputOriginInfo_t")]
unsafe impl quest_hook::libil2cpp::ThisArgument
for crate::OVR::OpenVR::InputOriginInfo_t {
    type Type = Self;
    fn matches(method: &quest_hook::libil2cpp::MethodInfo) -> bool {
        <Self as quest_hook::libil2cpp::Type>::matches_this_argument(method)
    }
    fn invokable(&mut self) -> *mut std::ffi::c_void {
        unsafe { quest_hook::libil2cpp::value_box(self) as *mut std::ffi::c_void }
    }
}
#[cfg(feature = "OVR+OpenVR+InputOriginInfo_t")]
impl crate::OVR::OpenVR::InputOriginInfo_t {
    pub fn get_rchRenderModelComponentName(
        &mut self,
    ) -> quest_hook::libil2cpp::Result<
        quest_hook::libil2cpp::Gc<quest_hook::libil2cpp::Il2CppString>,
    > {
        let __cordl_ret: quest_hook::libil2cpp::Gc<
            quest_hook::libil2cpp::Il2CppString,
        > = quest_hook::libil2cpp::ValueTypeExt::invoke(
            self,
            "get_rchRenderModelComponentName",
            (),
        )?;
        Ok(__cordl_ret.into())
    }
}
